export default function TermsOfUse() {
  return (
    <div className="min-h-screen bg-white dark:bg-black text-gray-900 dark:text-white">
      <main className="py-16 px-6">
        <div className="max-w-4xl mx-auto space-y-10">
          <h1 className="text-4xl font-bold text-center">Terms of Use</h1>
          <p className="text-lg text-center">
            Last Updated: <strong>January 2026</strong>
          </p>

          <section className="space-y-8 text-lg leading-relaxed">

            {/* 1 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">1. Acceptance of Terms</h2>
              <p>
                These Terms of Use (“Terms”) govern your access to and use of
                co-i.org and all related services (the “Platform”).
                By accessing or using the Platform, you agree to be bound by
                these Terms.
              </p>
            </div>

            {/* 2 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">2. About Co‑Intelligence</h2>
              <p>
                Co‑Intelligence (“we”, “us”) is an AI-powered intelligence platform
                designed to help organizations collect data, generate insights,
                and make informed decisions. The Platform provides analytics,
                AI recommendations, and decision-support tools.
              </p>
              <p className="mt-2">
                Co‑Intelligence is not a service provider for media, advertising,
                or talent management.
              </p>
            </div>

            {/* 3 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">3. Eligibility</h2>
              <ul className="list-disc ml-6 space-y-1">
                <li>You must be at least 18 years old</li>
                <li>You must have authority to act on behalf of an organization</li>
                <li>You must provide accurate and current account information</li>
              </ul>
            </div>

            {/* 4 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">4. Account Access & Security</h2>
              <p>
                You are responsible for safeguarding your credentials and all
                activity under your account. We may suspend or terminate access
                if security, compliance, or misuse concerns arise.
              </p>
            </div>

            {/* 5 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">5. Platform Use & Responsibility</h2>
              <p>
                You are solely responsible for your data inputs, analysis requests,
                and use of insights generated by the Platform. Compliance with
                applicable laws and internal policies is your responsibility.
              </p>
            </div>

            {/* 6 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">6. AI & Analytics</h2>
              <p>
                Co‑Intelligence provides AI-driven recommendations, analysis,
                and insights. AI outputs are probabilistic and informational only.
              </p>
              <p className="mt-2">
                Final decisions and actions based on the Platform’s insights
                remain the responsibility of the user.
              </p>
            </div>

            {/* 7 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">7. Reporting & Data</h2>
              <p>
                Data and insights are derived from integrated sources and
                analytics models. We do not guarantee accuracy, completeness,
                or outcomes.
              </p>
            </div>

            {/* 8 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">8. Fees & Billing</h2>
              <p>
                Platform fees, subscriptions, or enterprise agreements may apply.
                All fees are non-refundable unless otherwise stated in writing.
              </p>
            </div>

            {/* 9 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">9. Intellectual Property</h2>
              <p>
                Co‑Intelligence retains all rights to its software, AI models,
                workflows, and platform technology. Users retain ownership of
                their uploaded data.
              </p>
            </div>

            {/* 10 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">10. Prohibited Use</h2>
              <ul className="list-disc ml-6 space-y-1">
                <li>Misuse of AI or data systems</li>
                <li>Illegal, deceptive, or unauthorized activities</li>
                <li>Attempting to reverse-engineer the Platform</li>
                <li>Interfering with system integrity or security</li>
              </ul>
            </div>

            {/* 11 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">11. Third-Party Integrations</h2>
              <p>
                The Platform may integrate with analytics, data, or AI services.
                Use of these services is subject to their respective terms.
              </p>
            </div>

            {/* 12 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">12. Limitation of Liability</h2>
              <p>
                Co‑Intelligence is provided “as-is”. We are not liable for indirect,
                incidental, or consequential damages, lost revenue, or outcomes
                from use of the Platform.
              </p>
            </div>

            {/* 13 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">13. Termination</h2>
              <p>
                We may suspend or terminate access for violations, non-payment,
                or misuse. Upon termination, access to the Platform will cease.
              </p>
            </div>

            {/* 14 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">14. Governing Law</h2>
              <p>
                These Terms are governed by the laws of the State of Delaware,
                United States.
              </p>
            </div>

            {/* 15 */}
            <div>
              <h2 className="text-2xl font-bold mb-2">15. Contact</h2>
              <p>
                For legal inquiries, contact{" "}
                <a
                  href="mailto:info@co-i.org"
                  className="text-blue-600 dark:text-blue-400 underline"
                >
                  info@co-i.org
                </a>
                .
              </p>
            </div>

          </section>
        </div>
      </main>
    </div>
  );
}
